'use client'
import {PanelControl} from '@/components/PanelControl'
import Navigation from '../components/Navigation'
import MinimalNavigation from '../components/MinimalNavigation'
import './globals.css'
import { useState } from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import PrincipalSlider from '@/components/PrincipalSlider'


export default function RootLayout({ children }) {
  
  const metadata = {
    title: 'UNCP - Accesibilidad',
    description: 'Generated by create next app',
  }
  
  const [active, setActive] = useState(false)

  const changeActive = () => {
    setActive(!active)
  }

  return (
    <html lang="es">
      <head>
        <title>
          {metadata.title}
        </title>
      </head>
      
      <body className={'w-full dark:bg-green-950 font-normal'} >
      <PanelControl active={active} handleActive={changeActive}>
        <Header>
        </Header>
        <main className='flex flex-col w-full items-center relative'>
          <section className='w-full'>
              {children}
          </section>
        </main>
        <Footer/>
      </PanelControl>
      </body>
    </html>
  )
}
